Repository Kernel360/E2E2-TALKKA, pull requests merged in 2024-08, with the labels that each got.

#23 [FIX] ApiRespDto 변경사항 누락 반영
  server/src/main/java/com/talkka/server/common/exception/handler/RestControllerAdvice.java
Labels: ⌨️ BE, 🛠️ fix

#24 [FIX] BusReviewEntity에서 station_id 삭제
  server/src/main/java/com/talkka/server/review/dao/BusReviewEntity.java
Labels: ⌨️ BE, 🛠️ fix

#30 [FEAT] PR 빌드 체크봇 추가
  .github/workflows/pr-bot.yml
Labels: ✨ feat

#31 [FEAT] 네이버 소셜 인증 구현 #9
  server/build.gradle
  server/src/main/java/com/talkka/server/ServerApplication.java
  server/src/main/java/com/talkka/server/config/SecurityConfig.java
  server/src/main/java/com/talkka/server/oauth/OAuth2LoginFailureHandler.java
  server/src/main/java/com/talkka/server/oauth/OAuth2LoginSuccessHandler.java
  server/src/main/java/com/talkka/server/oauth/controller/AuthController.java
  server/src/main/java/com/talkka/server/oauth/domain/AuthUserDto.java
  server/src/main/java/com/talkka/server/oauth/domain/CustomUserPrincipal.java
  server/src/main/java/com/talkka/server/oauth/service/CustomOAuth2Service.java
  server/src/main/java/com/talkka/server/user/dao/UserEntity.java
  server/src/main/java/com/talkka/server/user/dao/UserRepository.java
  server/src/main/java/com/talkka/server/user/dto/UserCreateDto.java
  server/src/main/resources/application.yaml
Labels: ⌨️ BE, ✨ feat

#32 [FIX] 네이버 인증 구현 누락 수정 #9
  server/src/main/java/com/talkka/server/config/SecurityConfig.java
  server/src/main/java/com/talkka/server/oauth/OAuth2LoginFailureHandler.java
  server/src/main/java/com/talkka/server/oauth/OAuth2LoginSuccessHandler.java
  server/src/main/java/com/talkka/server/oauth/controller/AuthController.java
  server/src/main/java/com/talkka/server/oauth/domain/AuthUserDto.java
  server/src/main/java/com/talkka/server/oauth/domain/CustomUserPrincipal.java
  server/src/main/java/com/talkka/server/oauth/service/CustomOAuth2Service.java
  server/src/main/resources/static/index.html
  server/src/main/resources/templates/loginForm.html
  server/src/main/resources/templates/signUpForm.html
Labels: ⌨️ BE, 🛠️ fix

#36 [FEAT] 네이버 소셜 로그인 구현
  server/src/main/java/com/talkka/server/config/SecurityConfig.java
  server/src/main/java/com/talkka/server/oauth/OAuth2LoginFailureHandler.java
  server/src/main/java/com/talkka/server/oauth/OAuth2LoginSuccessHandler.java
  server/src/main/java/com/talkka/server/oauth/controller/AuthController.java
  server/src/main/java/com/talkka/server/oauth/controller/BaseController.java
  server/src/main/java/com/talkka/server/oauth/domain/AuthUserDto.java
  server/src/main/java/com/talkka/server/oauth/domain/CustomUserPrincipal.java
  server/src/main/java/com/talkka/server/oauth/domain/NaverOAuth2User.java
  server/src/main/java/com/talkka/server/oauth/domain/OAuth2UserInfo.java
  server/src/main/java/com/talkka/server/oauth/filter/UnregisteredUserFilter.java
  server/src/main/java/com/talkka/server/oauth/service/CustomOAuth2Service.java
  server/src/main/java/com/talkka/server/user/dao/UserRepository.java
  server/src/main/resources/templates/index.html
  server/src/main/resources/templates/loginForm.html
  server/src/main/resources/templates/signUpForm.html
Labels: ⌨️ BE, ✨ feat

#37 [FIX] 빌드 봇 캐싱 문제 해소
  .github/workflows/pr-bot.yml
Labels: ⌨️ BE, 🛠️ fix

#39 [FIX] userId OAuth2User 에서 누락된 문제 해결
  server/src/main/java/com/talkka/server/oauth/controller/BaseController.java
  server/src/main/java/com/talkka/server/oauth/domain/OAuth2UserInfo.java
  server/src/main/java/com/talkka/server/oauth/service/CustomOAuth2Service.java
  server/src/main/resources/templates/index.html
Labels: ⌨️ BE, 🛠️ fix

#33 [FEAT] 버스 관련 리뷰 CRUD 추가
  server/build.gradle
  server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
  server/src/main/java/com/talkka/server/review/dao/BusReviewEntity.java
  server/src/main/java/com/talkka/server/review/dao/BusReviewRepository.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewReqDto.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
  server/src/main/java/com/talkka/server/review/service/BusReviewService.java
  server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
Labels: ⌨️ BE, ✨ feat

#40 [REFACTOR] Code 형식으로 저장되는 Enum 리팩토링
  server/src/main/java/com/talkka/server/bus/enums/BusRouteType.java
  server/src/main/java/com/talkka/server/bus/enums/CenterStation.java
  server/src/main/java/com/talkka/server/bus/enums/DistrictCode.java
  server/src/main/java/com/talkka/server/bus/enums/EndBus.java
  server/src/main/java/com/talkka/server/bus/enums/LowPlate.java
  server/src/main/java/com/talkka/server/bus/enums/PlateType.java
  server/src/main/java/com/talkka/server/bus/enums/TurnStation.java
  server/src/main/java/com/talkka/server/bus/util/BusRouteTypeConverter.java
  server/src/main/java/com/talkka/server/bus/util/CenterStationConverter.java
  server/src/main/java/com/talkka/server/bus/util/DistrictCodeConverter.java
  server/src/main/java/com/talkka/server/bus/util/EndBusConverter.java
  server/src/main/java/com/talkka/server/bus/util/LowPlateConverter.java
  server/src/main/java/com/talkka/server/bus/util/PlateTypeConverter.java
  server/src/main/java/com/talkka/server/bus/util/TurnStationConverter.java
  server/src/main/java/com/talkka/server/common/util/EnumCodeConverter.java
  server/src/main/java/com/talkka/server/common/util/EnumCodeConverterUtils.java
  server/src/main/java/com/talkka/server/common/util/EnumCodeInterface.java
Labels: ⌨️ BE, ✨ feat

#43 [FEAT] 버스관련 API 구현
  server/src/main/java/com/talkka/server/bus/controller/BusRouteController.java
  server/src/main/java/com/talkka/server/bus/dao/BusRouteEntity.java
  server/src/main/java/com/talkka/server/bus/dao/BusRouteRepository.java
  server/src/main/java/com/talkka/server/bus/dao/BusRouteStationEntity.java
  server/src/main/java/com/talkka/server/bus/dao/BusRouteStationRepository.java
  server/src/main/java/com/talkka/server/bus/dao/BusStationEntity.java
  server/src/main/java/com/talkka/server/bus/dao/BusStationRepository.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusStationCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusStationRespDto.java
  server/src/main/java/com/talkka/server/bus/service/BusRouteService.java
  server/src/main/java/com/talkka/server/bus/service/BusRouteStationService.java
  server/src/main/java/com/talkka/server/bus/service/BusStationService.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
  server/src/test/java/com/talkka/server/bus/service/BusRouteServiceTest.java
  server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
Labels: ⌨️ BE, ✨ feat

#42 [REFACTOR] #8 busReview 관련 validate 추가 및 TimeSlot Enum 변경
  server/src/main/java/com/talkka/server/common/util/EnumCodeConverterUtils.java
  server/src/main/java/com/talkka/server/oauth/service/CustomOAuth2Service.java
  server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
  server/src/main/java/com/talkka/server/review/dao/BusReviewEntity.java
  server/src/main/java/com/talkka/server/review/dao/BusReviewRepository.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewReqDto.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
  server/src/main/java/com/talkka/server/review/enums/TimeSlot.java
  server/src/main/java/com/talkka/server/review/service/BusReviewService.java
  server/src/main/java/com/talkka/server/review/util/TimeSlotConverter.java
  server/src/main/java/com/talkka/server/user/dao/UserEntity.java
  server/src/main/java/com/talkka/server/user/dto/UserDto.java
  server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
Labels: ⌨️ BE, 📝 refactor

#50 [FEAT] 버스 노선, 정류장, 노선정류장 서비스 테스트 추가
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationCreateDto.java
  server/src/test/java/com/talkka/server/bus/service/BusFactory.java
  server/src/test/java/com/talkka/server/bus/service/BusRouteServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/BusRouteStationServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/BusStationServiceTest.java
Labels: ⌨️ BE, ✨ feat

#53 [FIX] dto 클래스 record 타입으로 리팩토링
  server/src/main/java/com/talkka/server/bus/dto/BusRouteCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusStationCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusStationRespDto.java
  server/src/main/java/com/talkka/server/bus/service/BusRouteService.java
  server/src/main/java/com/talkka/server/bus/service/BusRouteStationService.java
  server/src/main/java/com/talkka/server/bus/service/BusStationService.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewReqDto.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
  server/src/main/java/com/talkka/server/review/service/BusReviewService.java
  server/src/main/java/com/talkka/server/user/controller/UserController.java
  server/src/main/java/com/talkka/server/user/dto/UserCreateDto.java
  server/src/main/java/com/talkka/server/user/dto/UserCreateReqDto.java
  server/src/main/java/com/talkka/server/user/dto/UserDto.java
  server/src/main/java/com/talkka/server/user/dto/UserRespDto.java
  server/src/main/java/com/talkka/server/user/dto/UserUpdateReqDto.java
  server/src/main/java/com/talkka/server/user/service/UserService.java
  server/src/test/java/com/talkka/server/bus/service/BusStationServiceTest.java
  server/src/test/java/com/talkka/server/user/controller/UserControllerTest.java
  server/src/test/java/com/talkka/server/user/service/UserServiceTest.java
Labels: ⌨️ BE, ✨ feat

#51 [FEAT]: 소셜 로그인 과정 FE와 통합
  server/build.gradle
  server/src/main/java/com/talkka/server/config/SecurityConfig.java
  server/src/main/java/com/talkka/server/oauth/controller/AuthController.java
  server/src/main/java/com/talkka/server/oauth/enums/AuthRole.java
  server/src/main/java/com/talkka/server/oauth/filter/UnregisteredUserFilter.java
  server/src/main/java/com/talkka/server/oauth/service/CustomOAuth2Service.java
  server/src/main/resources/application.yaml
  server/src/main/resources/static/index.html
  server/src/main/resources/templates/index.html
  server/src/main/resources/templates/loginForm.html
  server/src/main/resources/templates/signUpForm.html
Labels: ⌨️ BE, ✨ feat

#58 [FEAT] 지하철에 관련된 엔티티 생성 및 레포지토리 구현
  server/src/main/java/com/talkka/server/common/enums/TimeSlot.java
  server/src/main/java/com/talkka/server/common/util/TimeSlotConverter.java
  server/src/main/java/com/talkka/server/review/dao/BusReviewEntity.java
  server/src/main/java/com/talkka/server/review/dao/BusReviewRepository.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewReqDto.java
  server/src/main/java/com/talkka/server/review/service/BusReviewService.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayConfusionEntity.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayConfusionRepository.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayStationEntity.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayStationRepository.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayTimetableEntity.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayTimetableRepository.java
  server/src/main/java/com/talkka/server/subway/enums/DayType.java
  server/src/main/java/com/talkka/server/subway/enums/Express.java
  server/src/main/java/com/talkka/server/subway/enums/Line.java
  server/src/main/java/com/talkka/server/subway/enums/SubwayTimeSlot.java
  server/src/main/java/com/talkka/server/subway/enums/Updown.java
  server/src/main/java/com/talkka/server/subway/util/DayTypeConverter.java
  server/src/main/java/com/talkka/server/subway/util/ExpressConverter.java
  server/src/main/java/com/talkka/server/subway/util/LineConverter.java
  server/src/main/java/com/talkka/server/subway/util/SubwayTimeSlotConverter.java
  server/src/main/java/com/talkka/server/subway/util/UpdownConverter.java
  server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
Labels: ⌨️ BE, ✨ feat

#62 [FEAT] BusApiService 구현
  .env.sample
  server/build.gradle
  server/src/main/java/com/talkka/server/api/core/config/ApiKeyProperty.java
  server/src/main/java/com/talkka/server/api/datagg/config/BusApiKeyProperty.java
  server/src/main/java/com/talkka/server/api/datagg/dto/BusLocationBodyDto.java
  server/src/main/java/com/talkka/server/api/datagg/dto/BusLocationRespDto.java
  server/src/main/java/com/talkka/server/api/datagg/dto/BusRouteInfoBodyDto.java
  server/src/main/java/com/talkka/server/api/datagg/dto/BusRouteInfoRespDto.java
  server/src/main/java/com/talkka/server/api/datagg/dto/BusRouteSearchBodyDto.java
  server/src/main/java/com/talkka/server/api/datagg/dto/BusRouteSearchRespDto.java
  server/src/main/java/com/talkka/server/api/datagg/dto/BusRouteStationBodyDto.java
  server/src/main/java/com/talkka/server/api/datagg/dto/BusRouteStationRespDto.java
  server/src/main/java/com/talkka/server/api/datagg/dto/PublicBusApiResp.java
  server/src/main/java/com/talkka/server/api/datagg/service/BusApiService.java
  server/src/main/java/com/talkka/server/api/datagg/service/BusApiServiceImpl.java
  server/src/main/resources/application.yaml
  server/src/test/java/com/talkka/server/api/datagg/service/BusApiServiceImplTest.java
  server/src/test/resources/application.yaml
Labels: ⌨️ BE, ✨ feat

#66 [FEAT] FE 통합에 따른 API 변경 (#65)
  server/src/main/java/com/talkka/server/bus/controller/BusRouteController.java
  server/src/main/java/com/talkka/server/bus/controller/BusRouteStationController.java
  server/src/main/java/com/talkka/server/bus/controller/BusStationController.java
  server/src/main/java/com/talkka/server/bus/dao/BusRouteRepository.java
  server/src/main/java/com/talkka/server/bus/dao/BusRouteStationRepository.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationRespDto.java
  server/src/main/java/com/talkka/server/bus/service/BusRouteService.java
  server/src/main/java/com/talkka/server/bus/service/BusRouteStationService.java
  server/src/main/java/com/talkka/server/bus/service/BusStationService.java
  server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
  server/src/main/java/com/talkka/server/review/dao/BusReviewRepository.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
  server/src/main/java/com/talkka/server/review/service/BusReviewService.java
  server/src/test/java/com/talkka/server/bus/BusTestFactory.java
  server/src/test/java/com/talkka/server/bus/controller/BusRouteControllerTest.java
  server/src/test/java/com/talkka/server/bus/service/BusRouteServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/BusRouteStationServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/BusStationServiceTest.java
  server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
Labels: ⌨️ BE, ✨ feat

#60 [FEAT] 지하철 역 조회 & 혼잡도 조회 서비스 구현
  server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayConfusionEntity.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayConfusionRepository.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayStationEntity.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayStationRepository.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayTimetableEntity.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayConfusionRespDto.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayStationReqDto.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayStationRespDto.java
  server/src/main/java/com/talkka/server/subway/enums/Line.java
  server/src/main/java/com/talkka/server/subway/enums/SubwayTimeSlot.java
  server/src/main/java/com/talkka/server/subway/service/SubwayConfusionService.java
  server/src/main/java/com/talkka/server/subway/service/SubwayStationService.java
  server/src/main/java/com/talkka/server/subway/util/SubwayTimeSlotConverter.java
  server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
  server/src/test/java/com/talkka/server/subway/service/SubwayConfusionServiceTest.java
  server/src/test/java/com/talkka/server/subway/service/SubwayStationServiceTest.java
Labels: ⌨️ BE, ✨ feat

#69 [FIX] YN Enum Error / RouteStation Controller Error / Like Query Error
  server/src/main/java/com/talkka/server/bus/controller/BusRouteStationController.java
  server/src/main/java/com/talkka/server/bus/dao/BusRouteRepository.java
  server/src/main/java/com/talkka/server/bus/dao/BusStationRepository.java
  server/src/main/java/com/talkka/server/bus/enums/CenterStation.java
  server/src/main/java/com/talkka/server/bus/enums/TurnStation.java
  server/src/main/java/com/talkka/server/bus/service/BusRouteService.java
  server/src/main/java/com/talkka/server/bus/service/BusStationService.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayStationRepository.java
  server/src/main/java/com/talkka/server/subway/service/SubwayStationService.java
  server/src/test/java/com/talkka/server/bus/service/BusRouteServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/BusStationServiceTest.java
  server/src/test/java/com/talkka/server/subway/service/SubwayStationServiceTest.java
Labels: ⌨️ BE, 🛠️ fix

#74 [FEAT] 북마크 엔티티 및 dto 구현
  server/src/main/java/com/talkka/server/bookmark/dao/BookmarkDetailEntity.java
  server/src/main/java/com/talkka/server/bookmark/dao/BookmarkEntity.java
  server/src/main/java/com/talkka/server/bookmark/dao/dto/BookmarkCreateDto.java
  server/src/main/java/com/talkka/server/bookmark/dao/dto/BookmarkDetailCreateDto.java
  server/src/main/java/com/talkka/server/bookmark/dao/dto/BookmarkDetailRespDto.java
  server/src/main/java/com/talkka/server/bookmark/dao/dto/BookmarkRespDto.java
  server/src/main/java/com/talkka/server/bookmark/enums/TransportType.java
  server/src/main/java/com/talkka/server/user/dao/UserEntity.java
  server/src/main/java/com/talkka/server/user/dto/UserDto.java
Labels: ⌨️ BE, ✨ feat

#79 [FIX]: TimeSlot conversion 이 get method에서 변경되지 않은 문제 해결
  server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
  server/src/main/java/com/talkka/server/review/service/BusReviewService.java
  server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
Labels: ⌨️ BE, 🛠️ fix

#80 [FIX] Enum code Exception 변경 및 Timeslot enum code 제거
  server/src/main/java/com/talkka/server/common/enums/TimeSlot.java
  server/src/main/java/com/talkka/server/common/exception/enums/InvalidEnumCodeException.java
  server/src/main/java/com/talkka/server/common/exception/handler/RestControllerAdvice.java
  server/src/main/java/com/talkka/server/common/util/EnumCodeConverter.java
  server/src/main/java/com/talkka/server/common/util/EnumCodeConverterUtils.java
  server/src/main/java/com/talkka/server/common/util/TimeSlotConverter.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayConfusionEntity.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayConfusionRespDto.java
  server/src/main/java/com/talkka/server/subway/service/SubwayConfusionService.java
  server/src/test/java/com/talkka/server/common/exception/handler/RestControllerAdviceTest.java
Labels: ⌨️ BE, 🛠️ fix

#82 [FEAT] 지하철 역 관련 코드 구현
  server/src/main/java/com/talkka/server/subway/controller/SubwayStationController.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayStationRepository.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayStationDto.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayStationReqDto.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayStationRespDto.java
  server/src/main/java/com/talkka/server/subway/enums/DayType.java
  server/src/main/java/com/talkka/server/subway/enums/Express.java
  server/src/main/java/com/talkka/server/subway/enums/Line.java
  server/src/main/java/com/talkka/server/subway/enums/Updown.java
  server/src/main/java/com/talkka/server/subway/exception/StationAlreadyExistsException.java
  server/src/main/java/com/talkka/server/subway/exception/StationNotFoundException.java
  server/src/main/java/com/talkka/server/subway/exception/enums/InvalidDayTypeEnumException.java
  server/src/main/java/com/talkka/server/subway/exception/enums/InvalidExpressEnumException.java
  server/src/main/java/com/talkka/server/subway/exception/enums/InvalidLineEnumException.java
  server/src/main/java/com/talkka/server/subway/exception/enums/InvalidUpdownEnumException.java
  server/src/main/java/com/talkka/server/subway/service/SubwayStationService.java
  server/src/test/java/com/talkka/server/subway/enums/DayTypeTest.java
  server/src/test/java/com/talkka/server/subway/enums/ExpressTest.java
  server/src/test/java/com/talkka/server/subway/enums/LineTest.java
  server/src/test/java/com/talkka/server/subway/enums/UpdownTest.java
  server/src/test/java/com/talkka/server/subway/service/SubwayStationServiceTest.java
Labels: ⌨️ BE, ✨ feat

#83 [REFACTOR]: User 관련 부분 VO / Exception refactor
  server/src/main/java/com/talkka/server/oauth/controller/AuthController.java
  server/src/main/java/com/talkka/server/oauth/service/CustomOAuth2Service.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
  server/src/main/java/com/talkka/server/user/controller/UserController.java
  server/src/main/java/com/talkka/server/user/dao/UserEntity.java
  server/src/main/java/com/talkka/server/user/dao/UserRepository.java
  server/src/main/java/com/talkka/server/user/dto/UserCreateDto.java
  server/src/main/java/com/talkka/server/user/dto/UserCreateReqDto.java
  server/src/main/java/com/talkka/server/user/dto/UserDto.java
  server/src/main/java/com/talkka/server/user/dto/UserRespDto.java
  server/src/main/java/com/talkka/server/user/dto/UserUpdateDto.java
  server/src/main/java/com/talkka/server/user/dto/UserUpdateReqDto.java
  server/src/main/java/com/talkka/server/user/exception/DuplicatedNicknameException.java
  server/src/main/java/com/talkka/server/user/exception/InvalidEmailException.java
  server/src/main/java/com/talkka/server/user/exception/InvalidNicknameException.java
  server/src/main/java/com/talkka/server/user/exception/UserNotFoundException.java
  server/src/main/java/com/talkka/server/user/service/UserService.java
  server/src/main/java/com/talkka/server/user/util/EmailDbConverter.java
  server/src/main/java/com/talkka/server/user/util/NicknameDbConverter.java
  server/src/main/java/com/talkka/server/user/vo/Email.java
  server/src/main/java/com/talkka/server/user/vo/Nickname.java
  server/src/test/java/com/talkka/server/user/controller/UserControllerTest.java
  server/src/test/java/com/talkka/server/user/service/UserServiceTest.java
  server/src/test/java/com/talkka/server/user/vo/EmailTest.java
  server/src/test/java/com/talkka/server/user/vo/NicknameTest.java
Labels: ⌨️ BE, 📝 refactor

#81 [FEAT] 북마크 서비스 구현
  server/src/main/java/com/talkka/server/bookmark/dao/BookmarkDetailRepository.java
  server/src/main/java/com/talkka/server/bookmark/dao/BookmarkEntity.java
  server/src/main/java/com/talkka/server/bookmark/dao/BookmarkRepository.java
  server/src/main/java/com/talkka/server/bookmark/dao/dto/BookmarkCreateDto.java
  server/src/main/java/com/talkka/server/bookmark/dao/dto/BookmarkRespDto.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkDetailReqDto.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkDetailRespDto.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkReqDto.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkRespDto.java
  server/src/main/java/com/talkka/server/bookmark/enums/TransportType.java
  server/src/main/java/com/talkka/server/bookmark/exception/BookmarkNotFoundException.java
  server/src/main/java/com/talkka/server/bookmark/exception/BookmarkUserNotFoundException.java
  server/src/main/java/com/talkka/server/bookmark/exception/enums/InvalidTransportTypeEnumException.java
  server/src/main/java/com/talkka/server/bookmark/service/BookmarkService.java
Labels: ⌨️ BE, ✨ feat

#86 [FEAT] 북마크 컨트롤러 구현 및 TransportType Enum 리팩토링
  server/src/main/java/com/talkka/server/bookmark/controller/BookmarkController.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkDetailRespDto.java
  server/src/main/java/com/talkka/server/bookmark/enums/TransportType.java
  server/src/main/java/com/talkka/server/bookmark/service/BookmarkService.java
Labels: ⌨️ BE, ✨ feat

#85 [FEAT] 지하철 혼잡도 관련 코드 구현
  server/src/main/java/com/talkka/server/subway/controller/SubwayConfusionController.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayConfusionEntity.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayConfusionRepository.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayConfusionRespDto.java
  server/src/main/java/com/talkka/server/subway/exception/ConfusionNotFoundException.java
  server/src/main/java/com/talkka/server/subway/service/SubwayConfusionService.java
  server/src/main/java/com/talkka/server/subway/service/SubwayStationService.java
  server/src/test/java/com/talkka/server/subway/service/SubwayConfusionServiceTest.java
Labels: ⌨️ BE, ✨ feat

#90 [FEAT] 지하철 리뷰 관련 구현
  data/mysql-files/add_constraints.sql
  data/mysql-files/schema.sql
  server/src/main/java/com/talkka/server/review/controller/SubwayReviewController.java
  server/src/main/java/com/talkka/server/review/dao/SubwayReviewEntity.java
  server/src/main/java/com/talkka/server/review/dao/SubwayReviewRepository.java
  server/src/main/java/com/talkka/server/review/dto/SubwayReviewDto.java
  server/src/main/java/com/talkka/server/review/dto/SubwayReviewReqDto.java
  server/src/main/java/com/talkka/server/review/dto/SubwayReviewRespDto.java
  server/src/main/java/com/talkka/server/review/exception/SubwayReviewNotFoundException.java
  server/src/main/java/com/talkka/server/review/service/SubwayReviewService.java
  server/src/main/resources/schema.sql
  server/src/test/java/com/talkka/server/review/service/SubwayReviewServiceTest.java
Labels: ⌨️ BE, ✨ feat

#88 [FEAT] 지하철 시간표 관련 코드 구현
  server/src/main/java/com/talkka/server/subway/controller/SubwayTimetableController.java
  server/src/main/java/com/talkka/server/subway/dao/SubwayTimetableRepository.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayTimetableRespDto.java
  server/src/main/java/com/talkka/server/subway/exception/TimetableNotFoundException.java
  server/src/main/java/com/talkka/server/subway/service/SubwayConfusionService.java
  server/src/main/java/com/talkka/server/subway/service/SubwayTimetableService.java
  server/src/test/java/com/talkka/server/subway/service/SubwayTimetableServiceTest.java
Labels: ⌨️ BE, ✨ feat

#94 [FEAT] ApiClientException 추가
  server/src/main/java/com/talkka/server/api/core/exception/ApiClientException.java
  server/src/main/java/com/talkka/server/api/datagg/service/BusApiService.java
  server/src/main/java/com/talkka/server/api/datagg/service/BusApiServiceImpl.java
Labels: ⌨️ BE, ✨ feat

#95 [REFACTOR]: 버스 도메인 리팩토링
  server/src/main/java/com/talkka/server/bus/controller/BusRouteController.java
  server/src/main/java/com/talkka/server/bus/controller/BusRouteStationController.java
  server/src/main/java/com/talkka/server/bus/controller/BusStationController.java
  server/src/main/java/com/talkka/server/bus/dao/BusRouteRepository.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusStationRespDto.java
  server/src/main/java/com/talkka/server/bus/enums/EndBus.java
  server/src/main/java/com/talkka/server/bus/exception/BusRouteNotFoundException.java
  server/src/main/java/com/talkka/server/bus/exception/BusRouteStationNotFoundException.java
  server/src/main/java/com/talkka/server/bus/exception/BusStationAlreadyExistsException.java
  server/src/main/java/com/talkka/server/bus/exception/BusStationNotFoundException.java
  server/src/main/java/com/talkka/server/bus/exception/RouteAlreadyExistsException.java
  server/src/main/java/com/talkka/server/bus/service/BusRouteService.java
  server/src/main/java/com/talkka/server/bus/service/BusRouteStationService.java
  server/src/main/java/com/talkka/server/bus/service/BusStationService.java
  server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
  server/src/main/java/com/talkka/server/review/exception/BusRouteNotFoundException.java
  server/src/main/java/com/talkka/server/review/exception/BusStationNotFoundException.java
  server/src/main/java/com/talkka/server/review/service/BusReviewService.java
  server/src/test/java/com/talkka/server/bus/BusTestFactory.java
  server/src/test/java/com/talkka/server/bus/controller/BusRouteControllerTest.java
  server/src/test/java/com/talkka/server/bus/service/BusRouteServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/BusRouteStationServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/BusStationServiceTest.java
  server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
Labels: ⌨️ BE, 📝 refactor

#96 [FEAT] 버스 위치 정보 수집 스케줄러 구현
  data/mysql-files/add_constraints.sql
  data/mysql-files/init_db.sql
  data/mysql-files/schema.sql
  server/src/main/java/com/talkka/server/api/datagg/dto/BusLocationBodyDto.java
  server/src/main/java/com/talkka/server/api/datagg/service/SimpleBusApiService.java
  server/src/main/java/com/talkka/server/bus/dao/BusLocationEntity.java
  server/src/main/java/com/talkka/server/bus/dao/BusRouteEntity.java
  server/src/main/java/com/talkka/server/bus/enums/EndBus.java
  server/src/main/java/com/talkka/server/bus/service/BlockedApiLocationCollectService.java
  server/src/main/java/com/talkka/server/bus/service/BusLocationCollectService.java
  server/src/main/java/com/talkka/server/bus/service/BusLocationService.java
  server/src/main/java/com/talkka/server/bus/service/LocationCollectingScheduler.java
  server/src/main/java/com/talkka/server/bus/util/ApiCallNumberProvider.java
  server/src/main/java/com/talkka/server/bus/util/BusLocationCollectProperty.java
  server/src/main/java/com/talkka/server/bus/util/BusLocationCollectProvider.java
  server/src/main/java/com/talkka/server/bus/util/LocationCollectingSchedulerConfigProperty.java
  server/src/main/java/com/talkka/server/bus/util/MinuteApiCallNumberProvider.java
  server/src/main/resources/application.yaml
  server/src/main/resources/schema.sql
  server/src/test/java/com/talkka/server/api/datagg/service/SimpleBusApiServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/BlockedApiLocationCollectServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/LocationCollectingSchedulerTest.java
Labels: ⌨️ BE, ✨ feat

#100 [FEAT] 권한별 API 접근 제한 및 개발용 세션 구현
  data/mysql-files/init_db.sql
  data/mysql-files/schema.sql
  server/src/main/java/com/talkka/server/bookmark/controller/BookmarkController.java
  server/src/main/java/com/talkka/server/bookmark/service/BookmarkService.java
  server/src/main/java/com/talkka/server/common/validator/ContentAccessValidator.java
  server/src/main/java/com/talkka/server/config/SecurityConfig.java
  server/src/main/java/com/talkka/server/oauth/controller/DevLoginController.java
  server/src/main/java/com/talkka/server/oauth/service/DevLoginService.java
  server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
  server/src/main/java/com/talkka/server/review/controller/SubwayReviewController.java
  server/src/main/java/com/talkka/server/review/service/BusReviewService.java
  server/src/main/java/com/talkka/server/review/service/SubwayReviewService.java
  server/src/main/java/com/talkka/server/subway/controller/SubwayStationController.java
  server/src/main/java/com/talkka/server/user/dao/UserEntity.java
  server/src/main/java/com/talkka/server/user/dto/UserCreateDto.java
  server/src/main/java/com/talkka/server/user/dto/UserDto.java
  server/src/main/java/com/talkka/server/user/enums/Grade.java
  server/src/main/resources/schema.sql
  server/src/test/java/com/talkka/server/common/validator/ContentAccessValidatorTest.java
  server/src/test/java/com/talkka/server/user/controller/UserControllerTest.java
  server/src/test/java/com/talkka/server/user/service/UserServiceTest.java
Labels: ⌨️ BE, ✨ feat, 📝 refactor

#105 [FEAT] Exception Handler 에서 Exception.class 에 대한 처리
  server/src/main/java/com/talkka/server/common/exception/handler/RestControllerAdvice.java
Labels: ⌨️ BE, ✨ feat

#107 [FEAT] HTTP Request / Response 기본 logging
  server/src/main/java/com/talkka/server/common/log/HttpLogMessage.java
  server/src/main/java/com/talkka/server/common/log/LoggingFilter.java
Labels: ⌨️ BE, ✨ feat

#108 [REVERT] "[FEAT] Exception Handler 에서 Exception.class 에 대한 처리"
  server/src/main/java/com/talkka/server/common/exception/handler/RestControllerAdvice.java
Labels: ⌨️ BE, 🔁 REVERT

#111 [FEAT] Controller 에 대한 권한 제어 재작성
  server/src/main/java/com/talkka/server/config/SecurityConfig.java
  server/src/main/java/com/talkka/server/oauth/controller/AuthController.java
  server/src/main/java/com/talkka/server/user/controller/UserController.java
Labels: ⌨️ BE, ✨ feat

#117 [FEAT] Springdoc OpenAPI 적용
  server/build.gradle
  server/src/main/java/com/talkka/server/bookmark/controller/BookmarkApi.java
  server/src/main/java/com/talkka/server/bookmark/controller/BookmarkController.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkDetailReqDto.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkDetailRespDto.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkRespDto.java
  server/src/main/java/com/talkka/server/bus/controller/BusRouteApi.java
  server/src/main/java/com/talkka/server/bus/controller/BusRouteController.java
  server/src/main/java/com/talkka/server/bus/controller/BusRouteStationApi.java
  server/src/main/java/com/talkka/server/bus/controller/BusRouteStationController.java
  server/src/main/java/com/talkka/server/bus/controller/BusStationApi.java
  server/src/main/java/com/talkka/server/bus/controller/BusStationController.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusStationCreateDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusStationRespDto.java
  server/src/main/java/com/talkka/server/common/dto/ErrorRespDto.java
  server/src/main/java/com/talkka/server/common/exception/handler/RestControllerAdvice.java
  server/src/main/java/com/talkka/server/config/SecurityConfig.java
  server/src/main/java/com/talkka/server/config/SwaggerConfig.java
  server/src/main/java/com/talkka/server/oauth/controller/AuthApi.java
  server/src/main/java/com/talkka/server/oauth/controller/AuthController.java
  server/src/main/java/com/talkka/server/oauth/controller/DevLoginApi.java
  server/src/main/java/com/talkka/server/oauth/controller/DevLoginController.java
  server/src/main/java/com/talkka/server/review/controller/BusReviewApi.java
  server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
  server/src/main/java/com/talkka/server/review/controller/SubwayReviewApi.java
  server/src/main/java/com/talkka/server/review/controller/SubwayReviewController.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewDto.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewReqDto.java
  server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
  server/src/main/java/com/talkka/server/review/dto/SubwayReviewDto.java
  server/src/main/java/com/talkka/server/review/dto/SubwayReviewRespDto.java
  server/src/main/java/com/talkka/server/subway/controller/SubwayConfusionApi.java
  server/src/main/java/com/talkka/server/subway/controller/SubwayConfusionController.java
  server/src/main/java/com/talkka/server/subway/controller/SubwayStationApi.java
  server/src/main/java/com/talkka/server/subway/controller/SubwayStationController.java
  server/src/main/java/com/talkka/server/subway/controller/SubwayTimetableApi.java
  server/src/main/java/com/talkka/server/subway/controller/SubwayTimetableController.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayConfusionRespDto.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayStationDto.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayStationRespDto.java
  server/src/main/java/com/talkka/server/subway/dto/SubwayTimetableRespDto.java
  server/src/main/java/com/talkka/server/user/controller/UserApi.java
  server/src/main/java/com/talkka/server/user/controller/UserController.java
  server/src/main/java/com/talkka/server/user/dto/UserCreateDto.java
  server/src/main/java/com/talkka/server/user/dto/UserDto.java
  server/src/main/java/com/talkka/server/user/dto/UserRespDto.java
  server/src/main/java/com/talkka/server/user/dto/UserUpdateDto.java
  server/src/main/java/com/talkka/server/user/vo/Email.java
  server/src/main/java/com/talkka/server/user/vo/Nickname.java
  server/src/main/resources/application.yaml
Labels: 📖 documentation, ⌨️ BE, ✨ feat

#121 [FEAT] 버스 실시간 도착 정보 연동 및 구현
  server/src/main/java/com/talkka/server/api/datagg/dto/BusArrivalBodyDto.java
  server/src/main/java/com/talkka/server/api/datagg/dto/BusArrivalRespDto.java
  server/src/main/java/com/talkka/server/api/datagg/service/BusApiService.java
  server/src/main/java/com/talkka/server/api/datagg/service/SimpleBusApiService.java
  server/src/main/java/com/talkka/server/bus/controller/BusLiveInfoApi.java
  server/src/main/java/com/talkka/server/bus/controller/BusLiveInfoController.java
  server/src/main/java/com/talkka/server/bus/dto/BusArrivalRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusLiveInfoRespDto.java
  server/src/main/java/com/talkka/server/bus/enums/RunningStatus.java
  server/src/main/java/com/talkka/server/bus/exception/GetBusLiveArrivalInfoFailedException.java
  server/src/main/java/com/talkka/server/bus/service/BusArrivalService.java
  server/src/main/java/com/talkka/server/bus/service/BusLiveInfoService.java
  server/src/main/java/com/talkka/server/bus/service/BusLiveInfoServiceImpl.java
  server/src/main/java/com/talkka/server/bus/service/CachedBusArrivalService.java
  server/src/main/java/com/talkka/server/bus/util/ArrivalCache.java
  server/src/main/java/com/talkka/server/common/util/CachedStorage.java
  server/src/main/java/com/talkka/server/common/util/MemoryCachedStorage.java
  server/src/main/java/com/talkka/server/common/util/TimeExpiredValue.java
Labels: ⌨️ BE, ✨ feat

#124 [FEAT] Bookmark 기능 수정
  data/mysql-files/init_db.sql
  data/mysql-files/schema.sql
  server/src/main/java/com/talkka/server/bookmark/controller/BookmarkApi.java
  server/src/main/java/com/talkka/server/bookmark/controller/BookmarkController.java
  server/src/main/java/com/talkka/server/bookmark/dao/BookmarkDetailEntity.java
  server/src/main/java/com/talkka/server/bookmark/dao/BookmarkDetailRepository.java
  server/src/main/java/com/talkka/server/bookmark/dao/BookmarkEntity.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkDetailReqDto.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkDetailRespDto.java
  server/src/main/java/com/talkka/server/bookmark/dto/BookmarkReqDto.java
  server/src/main/java/com/talkka/server/bookmark/enums/TransportType.java
  server/src/main/java/com/talkka/server/bookmark/exception/InvalidBusDetailException.java
  server/src/main/java/com/talkka/server/bookmark/exception/NotSupportedTypeException.java
  server/src/main/java/com/talkka/server/bookmark/service/BookmarkService.java
  server/src/main/java/com/talkka/server/bus/controller/BusLiveInfoController.java
  server/src/main/java/com/talkka/server/bus/dto/BusLiveInfoRespDto.java
  server/src/main/java/com/talkka/server/bus/dto/BusRouteStationRespDto.java
  server/src/main/java/com/talkka/server/bus/exception/BusRouteStationNotFoundException.java
  server/src/main/java/com/talkka/server/bus/exception/GetBusLiveArrivalInfoFailedException.java
  server/src/main/java/com/talkka/server/bus/service/BusArrivalService.java
  server/src/main/java/com/talkka/server/bus/service/BusLiveInfoService.java
  server/src/main/java/com/talkka/server/bus/service/BusLiveInfoServiceImpl.java
  server/src/main/java/com/talkka/server/bus/service/CachedBusArrivalService.java
  server/src/main/java/com/talkka/server/oauth/controller/AuthController.java
  server/src/main/java/com/talkka/server/review/exception/ContentAccessException.java
  server/src/main/resources/application.yaml
  server/src/main/resources/schema.sql
Labels: ⌨️ BE, ✨ feat

#126 [FEAT] FE 경로 / 리뷰 / 홈페이지 완성
  client/api/v1.d.ts
  client/app/bookmark/components/ArrivalInfo.tsx
  client/app/bookmark/components/BookmarkRoutes.tsx
  client/app/bookmark/components/BookmarkToggleList.tsx
  client/app/bookmark/components/BusEditCard.tsx
  client/app/bookmark/components/BusLiveInfoCard.tsx
  client/app/bookmark/components/CreateBookmark.tsx
  client/app/bookmark/components/EditBookmark.tsx
  client/app/bookmark/components/EditButton.tsx
  client/app/bookmark/components/InsertRoute.tsx
  client/app/bookmark/components/RefreshButton.tsx
  client/app/bookmark/components/RouteStationCard.tsx
  client/app/bookmark/components/SearchBusRoute.tsx
  client/app/bookmark/components/SelectRouteStation.tsx
  client/app/bookmark/page.tsx
  client/app/login/page.tsx
  client/app/mypage/modify/page.tsx
  client/app/mypage/page.tsx
  client/app/page.tsx
  client/app/review/bus/page.tsx
  client/app/route/components/Bookmark.tsx
  client/app/route/components/BookmarkDetail.tsx
  client/app/route/page.tsx
  client/config/site.ts
Labels: ✨ feat, 🌝 FE

#129 [FEAT] Logback rolling file 저장 적용
  .gitignore
  server/src/main/resources/logback.xml
Labels: ⌨️ BE, ✨ feat

#139 [FIX] logback.xml 로그 수집 레벨 수정
  server/src/main/resources/logback.xml
Labels: ⌨️ BE, 🛠️ fix

#125 [FEAT] EC2 환경 구성 및 CI/CD 구현
  .github/workflows/gradle-build.yml
  conf/nginx.conf
  docker-compose.yaml
  init-letsencrypt.sh
  server/Dockerfile
Labels: ⌨️ BE, ✨ feat

#140 [FEAT] 통계 정보 표현
  client/api/v1.d.ts
  client/app/bookmark/components/BookmarkRoutes.tsx
  client/app/bookmark/components/BusLiveInfoCard.tsx
  client/app/bookmark/components/EditBookmark.tsx
  client/app/page.tsx
  client/components/bus/ArrivalInfo.tsx
  client/components/bus/BusLiveInfoCard.tsx
  client/components/bus/BusSeatStatics.tsx
  client/components/bus/SearchBusRoute.tsx
  client/components/bus/SelectRouteStation.tsx
  client/components/ui/badge.tsx
  client/components/ui/chart.tsx
  client/package-lock.json
  client/package.json
  client/styles/globals.css
Labels: ⌨️ BE, ✨ feat

#142 [FIX] FE 빌드 에러 수정
  client/app/layout.tsx
  client/app/mypage/page.tsx
  client/app/review/subway/page.tsx
  client/components/icons.tsx
  client/components/main-nav.tsx
Labels: 🛠️ fix, 🌝 FE

#143 fix: ts dependency
  client/package.json
Labels: 🛠️ fix, 🌝 FE

#119 [FEAT] 관리자 페이지 구현
  server/src/main/java/com/talkka/server/admin/controller/AdminController.java
  server/src/main/java/com/talkka/server/admin/dao/CollectBusRouteEntity.java
  server/src/main/java/com/talkka/server/admin/dao/CollectBusRouteRepository.java
  server/src/main/java/com/talkka/server/admin/dto/BookmarkStatRespDto.java
  server/src/main/java/com/talkka/server/admin/dto/BusReviewStatRespDto.java
  server/src/main/java/com/talkka/server/admin/dto/CollectBusRouteCreateDto.java
  server/src/main/java/com/talkka/server/admin/dto/CollectBusRouteRespDto.java
  server/src/main/java/com/talkka/server/admin/exception/CollectBusRouteAlreadyExistsException.java
  server/src/main/java/com/talkka/server/admin/exception/CollectBusRouteNotFoundException.java
  server/src/main/java/com/talkka/server/admin/service/AdminService.java
  server/src/main/java/com/talkka/server/admin/service/CollectBusRouteService.java
  server/src/main/java/com/talkka/server/admin/util/CollectedRouteProvider.java
  server/src/main/java/com/talkka/server/admin/util/PersistenceCollectedRouteProvider.java
  server/src/main/java/com/talkka/server/admin/util/PropertyCollectedRouteProvider.java
  server/src/main/java/com/talkka/server/bookmark/dao/BookmarkDetailRepository.java
  server/src/main/java/com/talkka/server/bus/service/BlockedApiLocationCollectService.java
  server/src/main/java/com/talkka/server/bus/service/LocationCollectingScheduler.java
  server/src/main/java/com/talkka/server/bus/util/BusLocationCollectProvider.java
  server/src/main/java/com/talkka/server/review/dao/BusReviewRepository.java
  server/src/main/java/com/talkka/server/user/service/UserService.java
  server/src/main/resources/application.yaml
  server/src/main/resources/templates/admin/bookmark.html
  server/src/main/resources/templates/admin/collect-route-form.html
  server/src/main/resources/templates/admin/collect.html
  server/src/main/resources/templates/admin/index.html
  server/src/main/resources/templates/admin/review.html
  server/src/main/resources/templates/admin/user.html
  server/src/main/resources/templates/dev/dev-index.html
  server/src/test/java/com/talkka/server/bus/service/BlockedApiLocationCollectServiceTest.java
  server/src/test/java/com/talkka/server/bus/service/LocationCollectingSchedulerTest.java
  server/src/test/java/com/talkka/server/user/service/UserServiceTest.java
Labels: ⌨️ BE, ✨ feat

#144 [FEAT] 개발용 / 배포용 개발 환경 분리
  .github/workflows/gradle-build.yml
  docker-compose.yaml
  server/src/main/java/com/talkka/server/config/SecurityConfig.java
  server/src/main/resources/application.yaml
Labels: ⌨️ BE, ✨ feat

#148 [FEAT] 공공 api키 관리 기능 구현
  server/src/main/java/com/talkka/server/admin/controller/AdminController.java
  server/src/main/java/com/talkka/server/admin/controller/PublicApiKeyController.java
  server/src/main/java/com/talkka/server/admin/dao/PublicApiKeyEntity.java
  server/src/main/java/com/talkka/server/admin/dao/PublicApiKeyRepository.java
  server/src/main/java/com/talkka/server/admin/dto/PublicApiKeyRespDto.java
  server/src/main/java/com/talkka/server/admin/exception/PublicApiKeyAlreadyExistsException.java
  server/src/main/java/com/talkka/server/admin/exception/PublicApiKeyNotFoundException.java
  server/src/main/java/com/talkka/server/admin/service/PublicApiKeyService.java
  server/src/main/java/com/talkka/server/api/core/config/ApiKeyProperty.java
  server/src/main/java/com/talkka/server/api/core/config/ApiKeyProvider.java
  server/src/main/java/com/talkka/server/api/datagg/config/PersistenceApiKeyProvider.java
  server/src/main/java/com/talkka/server/api/datagg/config/PropertyApiKeyProvider.java
  server/src/main/java/com/talkka/server/api/datagg/service/SimpleBusApiService.java
  server/src/main/resources/templates/admin/collect-route-form.html
  server/src/main/resources/templates/admin/key.html
Labels: ⌨️ BE, ✨ feat

#131 [FEAT] RuntimeException Handler 추가
  server/src/main/java/com/talkka/server/common/exception/handler/RestControllerAdvice.java
Labels: ⌨️ BE, ✨ feat

#156 [FIX] 관리자-수집노선 컨트롤러 누락 해결
  server/src/main/java/com/talkka/server/admin/controller/CollectBusRouteController.java
Labels: ⌨️ BE, 🛠️ fix

#159 [FEAT] 프론트 서버 배포
  .github/workflows/gradle-build.yml
  client/.env.production
  client/.gitignore
  client/Dockerfile
  client/config/api.ts
  client/next.config.mjs
  conf/nginx.conf
  docker-compose.yaml
  server/src/main/java/com/talkka/server/oauth/controller/BaseController.java
  server/src/main/resources/application.yaml
Labels: ⌨️ BE, ✨ feat, 🌝 FE

#160 [FEAT] 커스텀 스케줄러 구현
  server/src/main/java/com/talkka/server/admin/controller/AdminController.java
  server/src/main/java/com/talkka/server/admin/controller/SchedulerController.java
  server/src/main/java/com/talkka/server/admin/dto/SchedulerReqDto.java
  server/src/main/java/com/talkka/server/admin/dto/SchedulerRespDto.java
  server/src/main/java/com/talkka/server/admin/exception/SchedulerNotFoundException.java
  server/src/main/java/com/talkka/server/admin/scheduler/DynamicScheduled.java
  server/src/main/java/com/talkka/server/admin/scheduler/DynamicSchedulingConfig.java
  server/src/main/java/com/talkka/server/api/datagg/config/PersistenceApiKeyProvider.java
  server/src/main/java/com/talkka/server/bus/service/LocationCollectingScheduler.java
  server/src/main/resources/templates/admin/index.html
  server/src/main/resources/templates/admin/scheduler.html
Labels: ⌨️ BE, ✨ feat

#161 [FIX] BE 배포 오류 수정
  .env.sample
  server/src/main/java/com/talkka/server/api/datagg/config/PropertyApiKeyProvider.java
  server/src/main/java/com/talkka/server/api/datagg/service/SimpleBusApiService.java
  server/src/main/resources/application.yaml
Labels: ⌨️ BE, 🛠️ fix

#162 [FIX] UI 오류 수정
  client/app/bookmark/components/BookmarkRoutes.tsx
  client/app/bookmark/components/CreateBookmark.tsx
  client/app/bookmark/components/EditBookmark.tsx
  client/app/bookmark/page.tsx
  client/app/layout.tsx
  client/app/mypage/modify/page.tsx
  client/app/mypage/page.tsx
  client/app/review/bus/page.tsx
  client/components/bus/BusSeatStatics.tsx
  client/components/site-header.tsx
  client/components/ui/command.tsx
  client/components/ui/input.tsx
  client/public/icon512_maskable.png
  client/public/icon512_rounded.png
  client/public/manifest.json
  client/styles/globals.css
Labels: ✨ feat, 🌝 FE

#168 [FIX] 스케줄러 리팩토링
  server/src/main/java/com/talkka/server/admin/controller/SchedulerController.java
  server/src/main/java/com/talkka/server/admin/exception/InvalidCronExpressionException.java
  server/src/main/java/com/talkka/server/admin/scheduler/DynamicSchedulingConfig.java
  server/src/main/java/com/talkka/server/bus/controller/BusLocationProcessController.java
  server/src/main/java/com/talkka/server/bus/dao/BusLocationRepository.java
  server/src/main/java/com/talkka/server/bus/service/BusLocationService.java
  server/src/main/resources/templates/admin/scheduler.html
Labels: ⌨️ BE, 🛠️ fix
